//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTestsUI.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityTestsUI.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACCONT.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string AddQuestionButtonText {
            get {
                return ResourceManager.GetString("AddQuestionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Question.
        /// </summary>
        internal static string AddQuestionTab {
            get {
                return ResourceManager.GetString("AddQuestionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADMIN.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Which Role This Question Will Be Displayed For.
        /// </summary>
        internal static string AdminRoles {
            get {
                return ResourceManager.GetString("AdminRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Questions:.
        /// </summary>
        internal static string AllQuestoinsLabel {
            get {
                return ResourceManager.GetString("AllQuestoinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answer was successfuly deleted.
        /// </summary>
        internal static string AnswerDeletedSuccess {
            get {
                return ResourceManager.GetString("AnswerDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answers.
        /// </summary>
        internal static string AnswersTab {
            get {
                return ResourceManager.GetString("AnswersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to Login.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correct Answers:.
        /// </summary>
        internal static string CorrectAnswersLabel {
            get {
                return ResourceManager.GetString("CorrectAnswersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correct Answers Percents:.
        /// </summary>
        internal static string CorrectAnswersPercentsLabel {
            get {
                return ResourceManager.GetString("CorrectAnswersPercentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Counter Of Used Tries.
        /// </summary>
        internal static string CounterOfUsedTries {
            get {
                return ResourceManager.GetString("CounterOfUsedTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Date Birthday.
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DateTimeOfLastTryByFireSafety.
        /// </summary>
        internal static string DateTimeOfLastTryByFireSafety {
            get {
                return ResourceManager.GetString("DateTimeOfLastTryByFireSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Try By Fire Safety:.
        /// </summary>
        internal static string DateTimeOfLastTryByFireSafetyLabel {
            get {
                return ResourceManager.GetString("DateTimeOfLastTryByFireSafetyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DateTimeOfLastTryByIndustrialSafety.
        /// </summary>
        internal static string DateTimeOfLastTryByIndustrialSafety {
            get {
                return ResourceManager.GetString("DateTimeOfLastTryByIndustrialSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Try By Industrial Safety:.
        /// </summary>
        internal static string DateTimeOfLastTryByIndustrialSafetyLabel {
            get {
                return ResourceManager.GetString("DateTimeOfLastTryByIndustrialSafetyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EmailAddress.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Employee report.
        /// </summary>
        internal static string EmployeesReport {
            get {
                return ResourceManager.GetString("EmployeesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter counter of used tries.
        /// </summary>
        internal static string EnterCounter {
            get {
                return ResourceManager.GetString("EnterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter RoleName.
        /// </summary>
        internal static string EnterRoleName {
            get {
                return ResourceManager.GetString("EnterRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Type.
        /// </summary>
        internal static string EnterType {
            get {
                return ResourceManager.GetString("EnterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EXIT.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fields Are Not Filled.
        /// </summary>
        internal static string FieldsAreNotFilled {
            get {
                return ResourceManager.GetString("FieldsAreNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pass the fire safety test.
        /// </summary>
        internal static string FireSafetyTestButton {
            get {
                return ResourceManager.GetString("FireSafetyTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter First Answer.
        /// </summary>
        internal static string FirstAnswerTextBox {
            get {
                return ResourceManager.GetString("FirstAnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter fourth Answer.
        /// </summary>
        internal static string FourthAnswerTextBox {
            get {
                return ResourceManager.GetString("FourthAnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Fields aren&apos;t filled in correctly.
        /// </summary>
        internal static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pass the industrial safety test.
        /// </summary>
        internal static string IndustrialSafetyTestButton {
            get {
                return ResourceManager.GetString("IndustrialSafetyTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Correct.
        /// </summary>
        internal static string IsCorrectAnswer {
            get {
                return ResourceManager.GetString("IsCorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log In.
        /// </summary>
        internal static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Login.
        /// </summary>
        internal static string LoginViewDescriptionLabel {
            get {
                return ResourceManager.GetString("LoginViewDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect data, please try again....
        /// </summary>
        internal static string LoginViewErrorMessage {
            get {
                return ResourceManager.GetString("LoginViewErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server timeout expired.
        /// </summary>
        internal static string LongTime {
            get {
                return ResourceManager.GetString("LongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to Security Tests.
        /// </summary>
        internal static string MainViewDescriptionLabel {
            get {
                return ResourceManager.GetString("MainViewDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Manager report.
        /// </summary>
        internal static string ManagersReport {
            get {
                return ResourceManager.GetString("ManagersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NEXT.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non vereficated.
        /// </summary>
        internal static string NonVereficated {
            get {
                return ResourceManager.GetString("NonVereficated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на out of.
        /// </summary>
        internal static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ********.
        /// </summary>
        internal static string PasswordBoxText {
            get {
                return ResourceManager.GetString("PasswordBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New question was seccessfuly added..
        /// </summary>
        internal static string QuestionAddSuccess {
            get {
                return ResourceManager.GetString("QuestionAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question was successfuly deleted.
        /// </summary>
        internal static string QuestionDeletedSuccess {
            get {
                return ResourceManager.GetString("QuestionDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на QuestionId.
        /// </summary>
        internal static string QuestionId {
            get {
                return ResourceManager.GetString("QuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Questions.
        /// </summary>
        internal static string QuestionsTab {
            get {
                return ResourceManager.GetString("QuestionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign up new user.
        /// </summary>
        internal static string RegisterTooltip {
            get {
                return ResourceManager.GetString("RegisterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Registration.
        /// </summary>
        internal static string RegisterViewDescriptionLabel {
            get {
                return ResourceManager.GetString("RegisterViewDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! Try again..
        /// </summary>
        internal static string RegisterViewErrorMessage {
            get {
                return ResourceManager.GetString("RegisterViewErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report By Employees.
        /// </summary>
        internal static string ReportByEmployees {
            get {
                return ResourceManager.GetString("ReportByEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report By Managers.
        /// </summary>
        internal static string ReportByManagers {
            get {
                return ResourceManager.GetString("ReportByManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report By Workers.
        /// </summary>
        internal static string ReportByWorkers {
            get {
                return ResourceManager.GetString("ReportByWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports.
        /// </summary>
        internal static string ReportsTab {
            get {
                return ResourceManager.GetString("ReportsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all fields.
        /// </summary>
        internal static string ResetTooltip {
            get {
                return ResourceManager.GetString("ResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role was successfuly added.
        /// </summary>
        internal static string RoleAddSuccess {
            get {
                return ResourceManager.GetString("RoleAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role was successfuly deleted.
        /// </summary>
        internal static string RoleDeletedSuccess {
            get {
                return ResourceManager.GetString("RoleDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RoleId.
        /// </summary>
        internal static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RoleName.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role name are not filled.
        /// </summary>
        internal static string RoleNameAreNotFilled {
            get {
                return ResourceManager.GetString("RoleNameAreNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Role.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roles.
        /// </summary>
        internal static string RolesTab {
            get {
                return ResourceManager.GetString("RolesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Second Answer.
        /// </summary>
        internal static string SecondAnswerTextBox {
            get {
                return ResourceManager.GetString("SecondAnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Up.
        /// </summary>
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are successfuly registered.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account was successfuly updated!.
        /// </summary>
        internal static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Test Results.
        /// </summary>
        internal static string TestResultsLabel {
            get {
                return ResourceManager.GetString("TestResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TESTS.
        /// </summary>
        internal static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Email.
        /// </summary>
        internal static string TextBoxEmail {
            get {
                return ResourceManager.GetString("TextBoxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Name.
        /// </summary>
        internal static string TextBoxName {
            get {
                return ResourceManager.GetString("TextBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Question.
        /// </summary>
        internal static string TextBoxQuestion {
            get {
                return ResourceManager.GetString("TextBoxQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Username.
        /// </summary>
        internal static string TextBoxUserName {
            get {
                return ResourceManager.GetString("TextBoxUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter UserPassword.
        /// </summary>
        internal static string TextBoxUserPassword {
            get {
                return ResourceManager.GetString("TextBoxUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Third Answer.
        /// </summary>
        internal static string ThirdAnswerTextBox {
            get {
                return ResourceManager.GetString("ThirdAnswerTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type was successfuly added.
        /// </summary>
        internal static string TypeAddSuccess {
            get {
                return ResourceManager.GetString("TypeAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type are not filled.
        /// </summary>
        internal static string TypeAreNotFilled {
            get {
                return ResourceManager.GetString("TypeAreNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type was successfuly deleted.
        /// </summary>
        internal static string TypeDeletedSuccess {
            get {
                return ResourceManager.GetString("TypeDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TypeOfQuestionId.
        /// </summary>
        internal static string TypeOfQuestionId {
            get {
                return ResourceManager.GetString("TypeOfQuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Type Of Question.
        /// </summary>
        internal static string TypesOfQuestion {
            get {
                return ResourceManager.GetString("TypesOfQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types Of Question.
        /// </summary>
        internal static string TypesTab {
            get {
                return ResourceManager.GetString("TypesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string UpdateAccountButton {
            get {
                return ResourceManager.GetString("UpdateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account data was successfuly changed.
        /// </summary>
        internal static string UpdateAccountSuccess {
            get {
                return ResourceManager.GetString("UpdateAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Answer was successfuly updated.
        /// </summary>
        internal static string UpdateAnswerSuccess {
            get {
                return ResourceManager.GetString("UpdateAnswerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question was successfuly updated.
        /// </summary>
        internal static string UpdateQuestionSuccess {
            get {
                return ResourceManager.GetString("UpdateQuestionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role was successfuly updated.
        /// </summary>
        internal static string UpdateRoleSuccess {
            get {
                return ResourceManager.GetString("UpdateRoleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type was successfuly updated.
        /// </summary>
        internal static string UpdateTypeSuccess {
            get {
                return ResourceManager.GetString("UpdateTypeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User was successfuly updated.
        /// </summary>
        internal static string UpdateUserSuccess {
            get {
                return ResourceManager.GetString("UpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string UpdateWindow {
            get {
                return ResourceManager.GetString("UpdateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User was successfuly added.
        /// </summary>
        internal static string UserAddSuccess {
            get {
                return ResourceManager.GetString("UserAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User was successfuly deleted.
        /// </summary>
        internal static string UserDeletedSuccess {
            get {
                return ResourceManager.GetString("UserDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Haven&apos;t passed yet.
        /// </summary>
        internal static string UserHaventPassedYet {
            get {
                return ResourceManager.GetString("UserHaventPassedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UserPassword.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        internal static string UsersTab {
            get {
                return ResourceManager.GetString("UsersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vereficated.
        /// </summary>
        internal static string Vereficated {
            get {
                return ResourceManager.GetString("Vereficated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vereficated by fire safety.
        /// </summary>
        internal static string VereficatedByFireSafety {
            get {
                return ResourceManager.GetString("VereficatedByFireSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vereficated by industrial safety.
        /// </summary>
        internal static string VereficatedByIndustrialSafety {
            get {
                return ResourceManager.GetString("VereficatedByIndustrialSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verefication Status By Fire Safety:.
        /// </summary>
        internal static string VereficationStatusByFireSafety {
            get {
                return ResourceManager.GetString("VereficationStatusByFireSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VereficationStatusByFireSafety.
        /// </summary>
        internal static string VereficationStatusByFireSafetyAdmin {
            get {
                return ResourceManager.GetString("VereficationStatusByFireSafetyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verefication Status By Industrial Safety:.
        /// </summary>
        internal static string VereficationStatusByIndustrialSafety {
            get {
                return ResourceManager.GetString("VereficationStatusByIndustrialSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VereficationStatusByIndustrialSafety.
        /// </summary>
        internal static string VereficationStatusByIndustrialSafetyAdmin {
            get {
                return ResourceManager.GetString("VereficationStatusByIndustrialSafetyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Workers report.
        /// </summary>
        internal static string WorkersReport {
            get {
                return ResourceManager.GetString("WorkersReport", resourceCulture);
            }
        }
    }
}
